server.port=8080

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

# Server config
resource.path=${RESOURCE_PATH}
server.origin=${SERVER_ORIGIN}

# Brevo Email API Key
brevo.api-key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}

# PortOne API key
portone.v2.api-secret=${PORTONE_V2_API_SECRET}

# SOLAPI API KEY
SOLAPI_API_KEY=${SOLAPI_API_KEY}
SOLAPI_API_SECRET=${SOLAPI_API_SECRET}
SOLAPI_FROM_NUMBER=${SOLAPI_FROM_NUMBER}


# MySQL properties
spring.datasource.url=jdbc:mysql://mysql:3306/ornably_db?${DB_OPTIONS}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# OAuth2
spring.security.oauth2.client.registration.google.client-id=${OAUTH2_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH2_GOOGLE_CLIENT_SECRET}

## Kakao Oauth2
spring.security.oauth2.client.registration.kakao.client-id=${OAUTH2_KAKAO_CLIENT_ID}
spring.security.oauth2.client.registration.kakao.redirect-uri=${SERVER_ORIGIN}/login/oauth2/code/kakao

## [NAVER] - OAUTH2
spring.security.oauth2.client.registration.naver.client-id=${OAUTH2_NAVER_CLIENT_ID}
spring.security.oauth2.client.registration.naver.client-secret=${OAUTH2_NAVER_CLIENT_SECRET}
spring.security.oauth2.client.registration.naver.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}