services:
  mysql:
    image: mysql:8.4
    container_name: ornably-mysql
    restart: unless-stopped
    environment:
      MYSQL_USER: "kevin" # 'kevin'@'%'
      MYSQL_PASSWORD: "kevin1234"
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "ornably_db"
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+09:00
    volumes:
      - ../data:/var/lib/mysql
      - ../../src/main/resources/SQL/1_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ../../src/main/resources/SQL/2_sample.sql:/docker-entrypoint-initdb.d/02-sample-data.sql:ro
      - ../../src/main/resources/SQL/3_account_sample.sql:/docker-entrypoint-initdb.d/03-account-sample.sql:ro
      - ../../src/main/resources/SQL/4_item_sample.sql:/docker-entrypoint-initdb.d/04-item-sample.sql:ro
      - ../../src/main/resources/SQL/5_event_sample.sql:/docker-entrypoint-initdb.d/05-event-sample.sql:ro
      - ../../src/main/resources/SQL/6_order_sample.sql:/docker-entrypoint-initdb.d/06-order-sample.sql:ro
      - ../../src/main/resources/SQL/7_user_item_sample.sql:/docker-entrypoint-initdb.d/07-user-item-sample.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2-alpine
    container_name: ornably-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ornably-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  ornably-redis-data:
