CREATE DATABASE IF NOT EXISTS kevin
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE kevin;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS CONNECT_LOG;
DROP TABLE IF EXISTS ORDERS_ITEM;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS WISHLIST;
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS ACCOUNT;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE ACCOUNT (
  ACCOUNT_PK INT NOT NULL AUTO_INCREMENT,
  ACCOUNT_ID VARCHAR(100) NULL,
  ACCOUNT_PASSWORD_HASH VARCHAR(255) NULL,
  ACCOUNT_NAME VARCHAR(100) NOT NULL,
  ACCOUNT_EMAIL VARCHAR(255) NULL,
  ACCOUNT_PHONE VARCHAR(30) NULL,
  ACCOUNT_DATE DATE NOT NULL DEFAULT (CURRENT_DATE),
  ACCOUNT_ROLE VARCHAR(30) NOT NULL DEFAULT 'LOCAL',
  ACCOUNT_EVENT_OPT_IN BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (ACCOUNT_PK),
  UNIQUE KEY UK_ACCOUNT_ID (ACCOUNT_ID),
  UNIQUE KEY UK_ACCOUNT_PHONE (ACCOUNT_PHONE),
  KEY IDX_ACCOUNT_ROLE (ACCOUNT_ROLE),
  KEY IDX_ACCOUNT_DATE (ACCOUNT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ITEM (
  ITEM_PK INT NOT NULL AUTO_INCREMENT,
  ITEM_NAME VARCHAR(255) NOT NULL,
  ITEM_PRICE INT NOT NULL DEFAULT 0,
  ITEM_STOCK INT NOT NULL DEFAULT 0,
  ITEM_IMAGE_URL VARCHAR(500) NULL,
  ITEM_DESCRIPTION TEXT NULL,
  ITEM_CATEGORY VARCHAR(100) NOT NULL,
  ITEM_REGIST_DATE DATE NOT NULL DEFAULT (CURRENT_DATE),
  PRIMARY KEY (ITEM_PK),
  KEY IDX_ITEM_CATEGORY (ITEM_CATEGORY),
  KEY IDX_ITEM_REGIST_DATE (ITEM_REGIST_DATE),
  KEY IDX_ITEM_NAME (ITEM_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE EVENT (
  EVENT_PK INT NOT NULL AUTO_INCREMENT,
  EVENT_NAME VARCHAR(255) NOT NULL,
  EVENT_IMAGE_URL VARCHAR(500) NULL,
  EVENT_START_DATE DATE NOT NULL,
  EVENT_END_DATE DATE NOT NULL,
  EVENT_TARGET_ACCOUNT JSON NOT NULL,
  EVENT_TARGET_CATEGORY JSON NOT NULL,
  EVENT_DISCOUNT_RATE INT NOT NULL DEFAULT 0,
  EVENT_DESCRIPTION TEXT NULL,
  PRIMARY KEY (EVENT_PK),
  KEY IDX_EVENT_DATE (EVENT_START_DATE, EVENT_END_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ADDRESS (
  ADDRESS_PK INT NOT NULL AUTO_INCREMENT,
  ACCOUNT_PK INT NOT NULL,
  ADDRESS_NAME VARCHAR(100) NOT NULL,
  ADDRESS_IS_DEFAULT BOOLEAN NOT NULL DEFAULT FALSE,
  ADDRESS_POSTAL_CODE VARCHAR(20) NOT NULL,
  ADDRESS_REGION VARCHAR(255) NOT NULL,
  ADDRESS_DETAIL VARCHAR(255) NOT NULL,
  PRIMARY KEY (ADDRESS_PK),
  KEY IDX_ADDRESS_ACCOUNT_PK (ACCOUNT_PK),
  CONSTRAINT FK_ADDRESS_ACCOUNT
    FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT (ACCOUNT_PK)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CART (
  CART_PK INT NOT NULL AUTO_INCREMENT,
  ACCOUNT_PK INT NOT NULL,
  ITEM_PK INT NOT NULL,
  CART_COUNT INT NOT NULL DEFAULT 1,
  PRIMARY KEY (CART_PK),
  UNIQUE KEY UK_CART_ACCOUNT_ITEM (ACCOUNT_PK, ITEM_PK),
  KEY IDX_CART_ITEM_PK (ITEM_PK),
  CONSTRAINT FK_CART_ACCOUNT
    FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT (ACCOUNT_PK)
    ON DELETE CASCADE,
  CONSTRAINT FK_CART_ITEM
    FOREIGN KEY (ITEM_PK) REFERENCES ITEM (ITEM_PK)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE WISHLIST (
  WISHLIST_PK INT NOT NULL AUTO_INCREMENT,
  ACCOUNT_PK INT NOT NULL,
  ITEM_PK INT NOT NULL,
  PRIMARY KEY (WISHLIST_PK),
  UNIQUE KEY UK_WISHLIST_ACCOUNT_ITEM (ACCOUNT_PK, ITEM_PK),
  KEY IDX_WISHLIST_ITEM_PK (ITEM_PK),
  CONSTRAINT FK_WISHLIST_ACCOUNT
    FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT (ACCOUNT_PK)
    ON DELETE CASCADE,
  CONSTRAINT FK_WISHLIST_ITEM
    FOREIGN KEY (ITEM_PK) REFERENCES ITEM (ITEM_PK)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE REVIEW (
  REVIEW_PK INT NOT NULL AUTO_INCREMENT,
  ACCOUNT_PK INT NOT NULL,
  ITEM_PK INT NOT NULL,
  REVIEW_TITLE VARCHAR(255) NOT NULL,
  REVIEW_CONTENT TEXT NOT NULL,
  REVIEW_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  REVIEW_STAR INT NOT NULL,
  REVIEW_IMAGE_URL VARCHAR(500) NULL,
  PRIMARY KEY (REVIEW_PK),
  UNIQUE KEY UK_REVIEW_ACCOUNT_ITEM (ACCOUNT_PK, ITEM_PK),
  KEY IDX_REVIEW_ITEM_PK (ITEM_PK),
  KEY IDX_REVIEW_ACCOUNT_PK (ACCOUNT_PK),
  KEY IDX_REVIEW_DATE (REVIEW_DATE),
  CONSTRAINT FK_REVIEW_ACCOUNT
    FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT (ACCOUNT_PK)
    ON DELETE CASCADE,
  CONSTRAINT FK_REVIEW_ITEM
    FOREIGN KEY (ITEM_PK) REFERENCES ITEM (ITEM_PK)
    ON DELETE CASCADE,
  CONSTRAINT CK_REVIEW_STAR CHECK (REVIEW_STAR BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ORDERS (
  ORDERS_PK INT NOT NULL AUTO_INCREMENT,
  ACCOUNT_PK INT NOT NULL,
  ORDERS_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADDRESS_NAME VARCHAR(100) NOT NULL,
  ORDERS_PAYMENT_TYPE VARCHAR(50) NOT NULL,
  ORDERS_IMPORT_UID VARCHAR(255) NOT NULL,
  ORDERS_MESSAGE TEXT NULL,
  ORDERS_STATUS VARCHAR(50) NOT NULL DEFAULT '상품 준비중',
  PRIMARY KEY (ORDERS_PK),
  UNIQUE KEY UK_ORDERS_IMPORT_UID (ORDERS_IMPORT_UID),
  KEY IDX_ORDERS_ACCOUNT_PK (ACCOUNT_PK),
  KEY IDX_ORDERS_DATE (ORDERS_DATE),
  CONSTRAINT FK_ORDERS_ACCOUNT
    FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT (ACCOUNT_PK)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ORDERS_ITEM (
  ORDERS_ITEM_PK INT NOT NULL AUTO_INCREMENT,
  ORDERS_PK INT NOT NULL,
  ITEM_PK INT NOT NULL,
  ORDERS_ITEM_COUNT INT NOT NULL,
  ORDERS_ITEM_PRICE INT NOT NULL,
  PRIMARY KEY (ORDERS_ITEM_PK),
  KEY IDX_ORDERS_ITEM_ORDERS_PK (ORDERS_PK),
  KEY IDX_ORDERS_ITEM_ITEM_PK (ITEM_PK),
  CONSTRAINT FK_ORDERS_ITEM_ORDERS
    FOREIGN KEY (ORDERS_PK) REFERENCES ORDERS (ORDERS_PK)
    ON DELETE CASCADE,
  CONSTRAINT FK_ORDERS_ITEM_ITEM
    FOREIGN KEY (ITEM_PK) REFERENCES ITEM (ITEM_PK)
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CONNECT_LOG (
  CONNECT_LOG_PK INT NOT NULL AUTO_INCREMENT,
  ACCOUNT_PK INT NOT NULL,
  CONNECT_IP VARCHAR(45) NULL,
  CONNECT_DEVICE VARCHAR(255) NULL,
  CONNECT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (CONNECT_LOG_PK),
  KEY IDX_CONNECT_LOG_ACCOUNT_DATE (ACCOUNT_PK, CONNECT_DATE),
  CONSTRAINT FK_CONNECT_LOG_ACCOUNT
    FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT (ACCOUNT_PK)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
